import dotenv from "dotenv";
dotenv.config();

const SHOPIFY_API_KEY = process.env.SHOPIFY_API_KEY;
const SHOPIFY_API_SECRET = process.env.SHOPIFY_API_SECRET;
const SHOPIFY_SCOPES = process.env.SHOPIFY_SCOPES;
const SHOPIFY_REDIRECT_URI = process.env.SHOPIFY_REDIRECT_URI;
const MONGO_URI = process.env.MONGO_URI;
const LOCATIONIQ_API_KEY = process.env.LOCATIONIQ_ACCESS_TOKEN;
const ADDRESS_API_ACCESS_TOKEN = process.env.ADDRESS_API_ACCESS_TOKEN;

export {
  SHOPIFY_API_KEY,
  SHOPIFY_API_SECRET,
  SHOPIFY_SCOPES,
  SHOPIFY_REDIRECT_URI,
  MONGO_URI,
  LOCATIONIQ_API_KEY,
  ADDRESS_API_ACCESS_TOKEN,
};
